apiVersion: apps/v1
kind: Deployment
metadata:
  name: Society_Management
spec:
  selector:
    matchLabels:
      app: Society_Management
  replicas: 1 
  template: 
    metadata:
      labels:
        app: Society_Management
    spec:
      containers:
      - name: Society_Management
        image: Society_Management_sina:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: Society_Management
spec:
  type: LoadBalancer
  selector:
    app: Society_Management
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
